---
- hosts: fcos
  gather_facts: false
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3
    password_max_days: 90
    password_min_days: 1
    ssh_port: 15762
    grub_user: core

  tasks:

    - name: AUTH-9216 - Remove unused entries from /etc/gshadow
      become: yes
      lineinfile:
        path: /etc/gshadow
        state: absent
        regexp: "{{ item }}"
      with_items:
        - "^audio:"
        - "^bin:"
        - "^cdrom:"
        - "^daemon:"
        - "^dialout:"
        - "^disk:"
        - "^floppy:"
        - "^ftp:"
        - "^games:"
        - "^kmem:"
        - "^kvm:"
        - "^lock:"
        - "^lp:"
        - "^mail:"
        - "^man:"
        - "^mem:"
        - "^nobody:"
        - "^printadmin:"
        - "^render:"
        - "^sys:"
        - "^systemd-coredump:"
        - "^tape:"
        - "^tty:"
        - "^users:"
        - "^video:"
      tags:
        - AUTH-9216

    - name: AUTH-9216 - Add sudo to /etc/gshadow to match /etc/group
      lineinfile:
        path: /etc/gshadow
        state: present
        regexp: "^sudo:"
        line: "sudo:x::core"
      tags:
        - AUTH-9216

    - name: AUTH-9216 - Add sudo to /etc/gshadow to match /etc/group
      lineinfile:
        path: /etc/gshadow
        state: present
        regexp: "^systemd-journal:"
        line: "systemd-journal:x::core"
      tags:
        - AUTH-9216

    - name: AUTH-9228 - Remove unused entries from /etc/shadow
      lineinfile:
        path: /etc/shadow
        state: absent
        regexp: "{{ item }}"
      with_items:
        - "^bin:"
        - "^daemon:"
        - "^adm:"
        - "^lp:"
        - "^sync:"
        - "^shutdown:"
        - "^halt:"
        - "^mail:"
        - "^operator:"
        - "^games:"
        - "^ftp:"
        - "^nobody:"
        - "^systemd-coredump:"
      tags:
        - AUTH-9228

    - name: AUTH-9252 - Check ownership and permissions for sudo configuration files
      file:
        path: /etc/sudoers.d/coreos-sudo-group
        state: file
        mode: 0440
      tags:
        - AUTH-9252

    - name: AUTH-9286 - PASS_MAX_DAYS - Checking user password aging
      lineinfile:
        path: /etc/login.defs
        state: present
        regexp: "^PASS_MAX_DAYS"
        line: "PASS_MAX_DAYS {{ password_max_days }}"
      tags:
        - AUTH-9286

    - name: AUTH-9286 - PASS_MIN_DAYS - Checking user password aging
      lineinfile:
        path: /etc/login.defs
        state: present
        regexp: "^PASS_MIN_DAYS"
        line: "PASS_MIN_DAYS {{ password_min_days }}"
      tags:
        - AUTH-9286

    - name: AUTH-9328 - Default umask values in /etc/login.defs
      copy:
        dest: /etc/profile.d/umask.sh
        content: |
          # By default, we want umask to get set. This sets it for login shell
          # Current threshold for system reserved uid/gids is 200
          # You could check uidgid reservation validity in
          # /usr/share/doc/setup-*/uidgid file
          if [ $UID -gt 199 ] && [ "`id -gn`" = "`id -un`" ]; then
              umask 007
          else
              umask 027
          fi
        mode: 644
      tags:
        - AUTH-9328

    # NIST recommends setting the daemon umask to 027 
    # (REHL5: http://nvd.nist.gov/scap/content/stylesheet/scap-rhel5-document.htm).
    #
    - name: AUTH-9328 - does /etc/init.d/functions exist?
      stat:
        path: /etc/init.d/functions
      register: auth9328

    - name: AUTH-9328 - Default umask values in /etc/init.d/functions
      lineinfile:
        path: /etc/init.d/functions
        state: present
        regexp: "^umask 022"
        line: "umask 027"
      when: auth9328.stat.exists      
      tags:
        - AUTH-9328

    - name: BOOT-5122- Installing template fur grub users.
      template:
        src: grub-fedora-coreos.j2
        dest: /etc/grub.d/01_users
        owner: root
        group: root
        mode: 0700
      tags: BOOT-5122

    - name: BOOT-5122 - add password
      lineinfile:
        dest: /etc/grub2.cfg
        regexp: "^password_pbkdf2 {{ grub_user }}"
        state: present
        insertafter: EOF
        line: "password_pbkdf2 {{ grub_user }} {{ grub_password }}"
      tags: BOOT-5122

    - name: BOOT-5122 - grub2-mkconfig
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      tags: BOOT-5122

    - name: SSH-7408 - hardening SSH configuration - AllowAgentForwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#AllowAgentForwarding"
        line: "AllowAgentForwarding no"
      tags:
        - SSH-7408

    - name: SSH-7408 - hardening SSH configuration - AllowTcpForwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#AllowTcpForwarding"
        line: "AllowTcpForwarding no"
      tags:
        - SSH-7408

    - name: SSH-7408 - hardening SSH configuration - ClientAliveCountMax
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#ClientAliveCountMax"
        line: "ClientAliveCountMax 2"
      tags:
        - SSH-7408

    - name: SSH-7408 - hardening SSH configuration - Compression
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#Compression"
        line: "Compression no"
      tags:
        - SSH-7408
        
    - name: SSH-7408 - hardening SSH configuration - INFO
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#LogLevel"
        line: "LogLevel VERBOSE"
      tags:
        - SSH-7408

    - name: SSH-7408 - hardening SSH configuration - MaxAuthTries
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#MaxAuthTries"
        line: "MaxAuthTries 3"
      tags:
        - SSH-7408

    - name: SSH-7408 - hardening SSH configuration - MaxSessions
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#MaxSessions"
        line: "MaxSessions 2"
      tags:
        - SSH-7408

    # - name: SSH-7408 - hardening SSH configuration - Port
    #   lineinfile:
    #     path: /etc/ssh/sshd_config
    #     state: present
    #     regexp: "^#Port"
    #     line: "Port {{ ssh_port }}"
    #   tags:
    #     - SSH-7408

    - name: SSH-7408 - hardening SSH configuration - TCPKeepAlive
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#TCPKeepAlive"
        line: "TCPKeepAlive no"
      tags:
        - SSH-7408

    - name: SSH-7408 - hardening SSH configuration - X11Forwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: "^#X11Forwarding"
        line: "X11Forwarding no"
      tags:
        - SSH-7408

    - name: STRG-1840 - Check if USB storage is disabled
      copy:
        dest: /etc/modprobe.d/usb.conf
        content: |
          blacklist usb-storage
      tags:
        - STRG-1840

    - name: STRG-1846 - Check if firewire storage is disabled
      copy:
        dest: /etc/modprobe.d/firewire.conf
        content: |
          blacklist firewire-core
      tags:
        - STRG-1846
